### ISSUE TITLE
Compatibility with Australis UI (Firefox 29+)

### ISSUE THREAD

**Issue by nohamelin** [nohamelin/simple-locale-switcher#3]
[Australis and add-on compatibility](https://developer.mozilla.org/en-US/Firefox/Australis_add-on_compat)
[Bug 872617 - (australis-cust) [meta] Australis Customization](https://bugzilla.mozilla.org/show_bug.cgi?id=872617)

**TO DO**
- [ ] ~~Let to use the classic XUL button in Australis.~~ _Dropped. Problematic. It can be taken up again, but it has a low priority_.

**RELEASED (0.7)**
- [x] Provide new sizes for the icon of the toolbar button.
- [x] Improve the appearance of the toolbar button when it's placed in the menu panel.
- [x] Rebuild the toolbar button as a subview-based widget (e.g. Developer, History buttons).
- [x] Add a workaround for [bug 998481](https://bugzilla.mozilla.org/show_bug.cgi?id=998481), specific to Firefox 29. It's fixed upstream for Fx30 and later.

**UPSTREAM**
- [ ] ~~Bad styling of toolbar button on hover when it's placed on the navigation toolbar, Linux. _Filled [bug 974236](https://bugzilla.mozilla.org/show_bug.cgi?id=974236)_~~ _It doesn't apply anymore with the button built as a widget_.
- [ ] ~~Visual issues when the toolbar button is placed in the menu panel; dropmarker missing in Linux _[bug 971246](https://bugzilla.mozilla.org/show_bug.cgi?id=971246) and [979610](https://bugzilla.mozilla.org/show_bug.cgi?id=979610)_~~ _It doesn't apply anymore with the button built as a widget_.
- [x] Clicking in a disabled item in the toolbar button closes the parent panel. _Fixed by [bug 946166](https://bugzilla.mozilla.org/show_bug.cgi?id=946166)._
- [x] The toolbar button isn't initialized on window load if it's placed in the menu panel. _Filled ~~[bug 941903](https://bugzilla.mozilla.org/show_bug.cgi?id=941903)~~. Marked as WONTFIX. Sigh. Added workaround_.
- [x] Ignored closemenu attribute of the restart checkbox in toolbar button when it's placed in menu panel or in the overflow panel. _Fixed by ~~[bug 941109](https://bugzilla.mozilla.org/show_bug.cgi?id=941109)~~_.
